extends:
- "stylelint-config-standard"
- "stylelint-config-prettier"
- "stylelint-config-recess-order"
- "stylelint-config-standard-scss"
- "stylelint-config-recommended-vue"
- "stylelint-config-recommended-vue/scss"
