# This is a basic workflow to help you get started with Actions

name: Deploy Release to Github Pages

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  release:
    types: [ published ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: checkout current repository
      uses: actions/checkout@v2
    
    - name: Use Node.js 14.x
      uses: actions/setup-node@v2
      with:
        node-version: 14.x
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: release-artifact
        path: dist
    
    - name: Checkout GitHub Pages Repository
      uses: actions/checkout@v2
      with:
        repository: Joe-Moran/album-site-public
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

    - name: Download a Build Artifact
      uses: actions/download-artifact@v2.1.0
    - run: |
          rsync -a release-artifact/* ./
          rm -r release-artifact
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated"
          git push



